services:
  # خدمة الويب لتطبيق Flask
  - type: web
    name: education-platform
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: education-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # سيقوم Render بإنشاء قيمة عشوائية آمنة
      - key: CLOUDINARY_CLOUD_NAME
        value: dhu8sbqml # القيمة من ملف .env
      - key: CLOUDINARY_API_KEY
        value: 246772366114445 # القيمة من ملف .env
      - key: CLOUDINARY_API_SECRET
        sync: false # مهم: لا تضع القيم السرية مباشرة هنا

  # خدمة العامل لتشغيل Celery
  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_worker.celery worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: education-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: dhu8sbqml
      - key: CLOUDINARY_API_KEY
        value: 246772366114445
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  # قاعدة بيانات PostgreSQL من Supabase (سنقوم بربطها يدوياً)
  - name: education-db
    ipAllowList: [] # اتركها فارغة للوصول من أي مكان

# خدمة Redis لـ Celery
- type: redis
  name: celery-redis